### PR TITLE
OXT-1546: Update CDN for Pure.CSS (purecss.io)

### PR DESCRIPTION
**Pull request by stacktrust**
- remove Yahoo/Verizon CDN
- add unpkg/Google/Cloudflare CDN

Signed-off-by: Rich Persaud <rich.persaud@baesystems.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
The URL matches the on https://purecss.io/start/. Is there a reason for leaving out `integrity` and `crossorigin`?

**Comment by stacktrust** [comment]
> The URL matches the on https://purecss.io/start/. Is there a reason for leaving out `integrity` and `crossorigin`?

Will fix, thanks for the review.

**Comment by stacktrust** [comment]
URL revised to match upstream guidance.

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
