### PR TITLE
Update page footer links

### PR DESCRIPTION
**Pull request by richpersaud**
1. Change Github wiki url to Confluence url and Atlassian icon.
2. Add "Source" link to Github
3. Remove link to Twitter account, since it is not currently used for marketing.  The footer link can be restored by changing the _config.yml file.

### CODE REVIEW

**Comment by rossphilipson** [comment]
LGTM, will merge soon.

**Comment by rossphilipson** [comment]
Actually there seems to be something wrong with your PR - where did that merge commit come from?

**Comment by richpersaud** [comment]
I was worried about that, it came from syncing my fork with upstream, using the Github web UI.  It is supposedly a supported alternative to using a local Git client to sync with a fork with an upstream remote.

**Comment by rossphilipson** [comment]
Doing it that way is not really a supported way and it will leave an artifact in the main OpenXT repo that does not make any sense in being there. This is really the way though you could probably find other tools to do the same thing:

https://help.github.com/articles/syncing-a-fork/

**Comment by rossphilipson** [comment]
@richpersaud - If you are stuck because you want to use your iPad to do this, maybe try this: http://git2go.com/   :)

**Comment by richpersaud** [comment]
Thanks for the iOS git client pointer :)  I've been using http://workingcopyapp.com, which generally works but became a bit confused when I added the upstream remote.  Will resubmit the PR.

**Pull request closed without merging**
